In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('rwa_data.db')
c = conn.cursor()

In [3]:
list_tables = """
    SELECT name FROM sqlite_master
    WHERE type='table';
"""
c.execute(list_tables)
print(c.fetchall())

[('RWA_122022',), ('RWA_032023',)]

In [4]:
rwa_1202 = pd.read_sql('''
            SELECT * FROM RWA_122022
            ''', 
            conn
)

In [7]:
rwa_1202.head(10)

,CLIENT_NUMBER,ACCOUNT_NUMBER,PRODUCT,STATUS,SEGMENT,EXPOSURE_DRAWN,EXPOSURE_UNDRAWN,EXPOSURE,EAD,EAD_COLL,PD,LGD,SIZE,MATURITY,F_MORTGAGE,F_REVOLVING,F_LARGE_FIN,RW,RWA
0,sfman997ux8036,1324710203qiph20,CREDIT_CARD,Performing,Retail,0.000000,18728.138760,18728.138760,11004.657130,0.00000,0.024652,0.309200,42.580298,1.156164,N,Y,N,0.245014,2696.291657
1,onvse705ca9217,1850135799zydg91,MORTGAGE,Performing,Retail,103838.774000,0.000000,103838.774000,105912.214700,55687.82851,0.005696,0.197270,44.995204,5.000000,Y,N,N,0.178579,18913.691050
2,icbpv275om2612,6219058663wnxv78,CONSUMER,Performing,Retail,4880.214964,0.000000,4880.214964,4907.859563,0.00000,0.173298,0.221800,44.995204,2.106849,N,N,N,0.493067,2419.902879
3,ybmbx119zx4306,7377738634wcur96,REVOLVING,Performing,Retail,4750.102454,38791.874580,43541.977040,26380.713480,0.00000,0.371520,0.631000,0.165181,1.000000,N,N,N,1.771476,46732.802610
4,zedzi814ms9207,7056331781sxng56,CREDIT_CARD,Performing,Retail,0.000000,3830.218120,3830.218120,1573.836625,0.00000,0.010971,0.549000,0.415023,1.000000,N,N,N,0.615273,968.339510
5,ejofd586kr7627,9789072963uchp67,CREDIT_CARD,Performing,Retail,37.459533,2835.204057,2872.663590,1713.898126,0.00000,0.001210,0.309200,44.995204,1.000000,N,Y,N,0.023115,39.617049
6,dbzwr812ui3544,6427437957qrog26,MORTGAGE,Performing,Retail,135123.325400,0.000000,135123.325400,137821.407600,86977.97194,0.003393,0.153466,44.995204,5.000000,Y,N,N,0.096183,13256.134650
7,aypqw778tr5906,6879704043radp38,DEBIT_CARD,Performing,Retail,1804.578540,118.602704,1923.181245,1899.634979,0.00000,0.092279,0.309200,44.995204,2.500000,N,Y,N,0.583528,1108.489564
8,zhhgl998px1432,2117007777qyxy90,CREDIT_CARD,Performing,Retail,2736.958962,178.114718,2915.073680,2849.059871,0.00000,0.034208,0.424800,0.126991,1.413699,N,Y,N,0.423945,1207.845309
9,vakyy255or8044,5397888782ghfy69,MORTGAGE,Performing,Retail,67845.074880,0.000000,67845.074880,68413.057920,63460.09754,0.001833,0.019880,44.995204,5.000000,Y,N,N,0.007924,542.093150